services:
  - type: web
    name: accessibility-analyzer-server
    env: node
    plan: free
    buildCommand: "npm install && npx playwright install chromium"
    startCommand: "node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: false
    autoDeploy: true
