services:
  - type: web
    name: accessibility-analyzer-server
    env: node
    plan: free
    buildCommand: "npm ci && npx playwright install chromium && ls -la /opt/render/.cache/ms-playwright/"
    startCommand: "node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: false
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/opt/render/.cache/ms-playwright"
    autoDeploy: true
