services:
  - type: web
    name: accessibility-analyzer-server
    env: node
    plan: free
    buildCommand: "npm ci && PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install chromium"
    startCommand: "node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: false
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
    autoDeploy: true
